language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install -r test-requirements.txt
  - pip install -r requirements.txt

script:
  - pytest -v tests/  --doctest-modules --cov idex --cov-report term-missing

after_success:
  - coveralls
